#ifndef ENUMDEF_H
#define ENUMDEF_H
typedef enum {	META_COMMAND_SUCCESS,	META_COMMAND_UNRECOGNIZED_COMMAND} MetaCommandResult;

typedef enum {	PREPARE_SUCCESS, PREPARE_UNRECOGNIZED_STATEMENT, PREPARE_SYNTAX_ERROR, PREPARE_STRING_TOO_LONG, PREPARE_NEGATIVE_ID} PrepareResult;

typedef enum {	STATEMENT_INSERT, STATEMENT_SELECT} StatementType;

typedef enum {EXEC_SUCCESS, EXEC_TABLE_FULL, EXEC_FAIL} ExecResult;
#endif


